name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    name: ${{ matrix.image }}:${{ matrix.tag }}
    container:
      image: ${{ matrix.repo }}/${{ matrix.image }}:${{ matrix.tag }}
      options: --privileged --cap-add=SYS_ADMIN

    strategy:
      fail-fast: false
      matrix:
        include:
        - {image: 'fedora', tag: 'rawhide',  repo: 'registry.fedoraproject.org'}
        - {image: 'centos', tag: 'stream9',  repo: 'quay.io/centos', args: 'OFFLINE=1' }
        - {image: 'centos', tag: 'stream10', repo: 'quay.io/centos', args: 'OFFLINE=1' }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Fedora)
        if: ${{ matrix.image == 'fedora' }}
        run: dnf install -y make R-core spectool mock

      - name: Install dependencies (CentOS)
        if: ${{ matrix.image == 'centos' }}
        run: |
          dnf config-manager --set-enabled crb
          dnf install -y epel-release
          dnf install -y epel-rpm-macros diffutils make R-core

      - name: Run tests
        run: make test ${{ matrix.args }}
