name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rawhide:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:rawhide
      options: --privileged --cap-add=SYS_ADMIN

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: dnf install -y make R-core spectool mock

      - name: Run tests
        run: make test

  epel9:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
      options: --privileged --cap-add=SYS_ADMIN

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --set-enabled crb
          dnf install -y epel-rpm-macros
          dnf install -y make R-core

      - name: Run tests
        run: make test OFFLINE=1

  epel10:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream10
      options: --privileged --cap-add=SYS_ADMIN

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --set-enabled crb
          dnf install -y epel-rpm-macros
	  dnf install -y make R-core

      - name: Run tests
        run: make test OFFLINE=1
